name: MinGW CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
    - name: make
      run: make solve_bs64.exe
